version: "3.6"
services:
  base:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - 8888:8888
    user: root
    environment:
      NB_USER: docker_worker
      NB_UID: 1008
      NB_GID: 1011
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: -R